<section x-show="activeNav==='system'" x-cloak class="dedicated-page">
    <div class="dedicated-page-head"><div><span>Configurare tehnică</span><h2>Setările sistemului</h2><p>Parametrii principali ai invertorului, rețelei și instalației.</p></div><div class="page-summary-pill"><b x-text="formatW(initial.inverter.nominal_power_w)"></b><small>invertor</small></div></div>
    <div class="system-page-grid">
        <section class="solar-card p-5">
            <div class="card-heading"><h2>Invertor</h2><span class="status-online"><i></i> Online</span></div>
            <div class="system-hero"><span>◈</span><div><b x-text="initial.inverter.name"></b><small>Invertor hibrid</small></div></div>
            <dl class="page-details"><div><dt>Putere nominală</dt><dd x-text="formatW(initial.inverter.nominal_power_w)"></dd></div><div><dt>Putere PV maximă</dt><dd x-text="formatW(initial.inverter.max_pv_power_w)"></dd></div><div><dt>Randament</dt><dd x-text="Number(initial.inverter.efficiency).toFixed(1)+'%'"></dd></div><div><dt>Putere backup</dt><dd x-text="formatW(initial.inverter.max_backup_power_w)"></dd></div></dl>
            <div class="consumer-section-title"><span>Modele SolarTech</span><small x-text="inverterPresets.length+' opțiuni'"></small></div>
            <div class="inverter-catalog"><template x-for="preset in inverterPresets" :key="preset.key"><article><span>◈</span><div><b x-text="preset.name"></b><small><span x-text="formatW(preset.nominal_power_w)"></span> · <span x-text="preset.phases===3?'Trifazat':'Monofazat'"></span> · <span x-text="preset.mppt_count+' MPPT'"></span></small><a :href="preset.source_url" target="_blank" rel="noreferrer">Fișă produs ↗</a></div><button type="button" @click="selectInverter(preset)" :disabled="inverterBusy || initial.inverter.name===preset.name" x-text="initial.inverter.name===preset.name?'Selectat':'Selectează'"></button></article></template></div>
        </section>
        <section class="solar-card p-5"><div class="card-heading"><h2>Conexiune și funcționare</h2></div><label class="system-control"><span><b>Conexiune la rețea</b><small>Permite importul și exportul energetic</small></span><input type="checkbox" x-model="gridAvailable" @change="tick()"></label><label class="system-select"><span>Mod rețea</span><select x-model="gridMode" @change="tick()"><option value="prosumer">Prosumator</option><option value="zero_export">Zero export</option><option value="limited">Import limitat</option><option value="offline">Offline / EPS</option></select></label><div class="system-stats"><div><small>Panouri</small><b x-text="enabledPanelCount"></b></div><div><small>Consumatori</small><b x-text="enabledConsumerUnitCount"></b></div><div><small>Baterie</small><b x-text="initial.battery.enabled?'Activă':'Nu'"></b></div></div></section>
    </div>
</section>
