<!DOCTYPE html>
<html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>EnerSim · Simulator fotovoltaic</title><meta name="description" content="Simulator interactiv de management energetic fotovoltaic"><link rel="preconnect" href="https://fonts.bunny.net"><link href="https://fonts.bunny.net/css?family=manrope:400,500,600,700,800" rel="stylesheet">@vite(['resources/css/app.css','resources/css/app.scss','resources/js/app.js'])</head>
<body class="font-sans antialiased" x-data="energySimulator({{ Illuminate\Support\Js::from($simulatorData) }})">
<div class="min-h-screen lg:flex">
<aside class="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-slate-800/80 bg-[#080d17] lg:flex lg:flex-col">
 <div class="flex h-20 items-center gap-3 px-6"><div class="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-amber-300 to-orange-500 text-xl text-slate-950">☀</div><div><div class="text-lg font-extrabold tracking-tight">ENER<span class="text-amber-400">SIM</span></div><div class="text-[10px] font-bold tracking-[.25em] text-slate-500">ENERGY LAB</div></div></div>
 <div class="px-3"><a href="{{ route('projects.index') }}" class="mb-3 flex items-center gap-3 rounded-xl border border-slate-800 px-4 py-3 text-xs font-bold text-slate-400 hover:border-sky-400/30 hover:text-sky-300">← Toate proiectele</a><div class="mb-3 rounded-xl bg-slate-900 p-3"><small class="block text-[9px] font-bold uppercase tracking-wider text-slate-600">Proiect activ</small><b class="mt-1 block truncate text-xs">{{ $project->name }}</b><span class="text-[10px] text-slate-500">{{ $project->city }}, {{ $project->county }}</span></div></div>
 <nav class="space-y-1 px-3 py-2"><template x-for="item in [{id:'dashboard',icon:'⌂',name:'Dashboard'},{id:'system',icon:'◈',name:'Sistem'},{id:'panels',icon:'▦',name:'Panouri'},{id:'consumers',icon:'ϟ',name:'Consumatori'},{id:'battery',icon:'▣',name:'Baterie'},{id:'grid',icon:'⌁',name:'Rețea'},{id:'simulation',icon:'▶',name:'Simulare'},{id:'scenarios',icon:'◇',name:'Scenarii'},{id:'reports',icon:'▤',name:'Rapoarte'}]"><button @click="tab=item.id" :class="tab===item.id?'bg-sky-400/10 text-sky-300 border-sky-400/20':'text-slate-500 border-transparent hover:text-slate-200'" class="flex w-full items-center gap-3 rounded-xl border px-4 py-2.5 text-sm font-semibold transition"><span class="w-5 text-center text-base" x-text="item.icon"></span><span x-text="item.name"></span></button></template></nav>
 <div class="mt-auto p-4"><div class="rounded-2xl border {{ $assessment['status']==='adequate'?'border-emerald-500/15 bg-emerald-500/5':'border-amber-500/15 bg-amber-500/5' }} p-4"><div class="mb-2 flex items-center gap-2 text-xs font-bold {{ $assessment['status']==='adequate'?'text-emerald-300':'text-amber-300' }}"><i class="pulse-live size-2 rounded-full bg-current"></i>{{ mb_strtoupper($assessment['label']) }}</div><p class="text-xs leading-5 text-slate-500">{{ number_format($assessment['pv_w']/1000,2) }} kWp · {{ number_format($assessment['continuous_w']/1000,2) }} kW sarcină<br>Scor dimensionare {{ $assessment['score'] }}%</p></div></div>
</aside>
<main class="min-w-0 flex-1 lg:ml-64">
 <header class="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-slate-800/70 bg-[#070b14]/90 px-4 backdrop-blur-xl sm:px-8"><div><p class="text-[10px] font-bold uppercase tracking-[.25em] text-sky-400">{{ $project->name }}</p><h1 class="text-xl font-extrabold" x-text="tab==='dashboard'?'Flux energetic live':tab==='panels'?'Solar Array Designer':tab==='consumers'?'Management consumatori':'EnerSim Control'">Flux energetic live</h1></div><div class="flex items-center gap-3"><div class="hidden text-right sm:block"><div class="font-mono text-sm font-bold" x-text="time.toLocaleString('ro-RO',{dateStyle:'medium',timeStyle:'short'})"></div><div class="text-[10px] uppercase tracking-wider text-slate-500"><span x-text="speed+'×'">10×</span> · <span x-text="weatherLabel"></span></div></div><button @click="failGrid" :class="gridAvailable?'border-rose-500/30 text-rose-300':'bg-emerald-500/15 border-emerald-500/30 text-emerald-300'" class="rounded-xl border px-3 py-2 text-xs font-bold" x-text="gridAvailable?'Simulează pana':'Repornește rețeaua'"></button></div></header>
 <div class="p-4 sm:p-8">
  <section x-show="tab==='dashboard' || !['panels','consumers'].includes(tab)" x-cloak>
   <div class="mb-5 rounded-3xl border p-5 {{ $assessment['status']==='adequate'?'border-emerald-400/20 bg-emerald-400/5':($assessment['status']==='partial'?'border-amber-400/20 bg-amber-400/5':'border-rose-400/20 bg-rose-400/5') }}">
    <div class="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div class="flex items-start gap-4"><div class="grid size-14 shrink-0 place-items-center rounded-2xl text-2xl {{ $assessment['status']==='adequate'?'bg-emerald-400/15':'bg-amber-400/15' }}">{{ $assessment['status']==='adequate'?'✓':'!' }}</div><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Verdict dimensionare</p><h2 class="mt-1 text-xl font-black {{ $assessment['status']==='adequate'?'text-emerald-300':($assessment['status']==='partial'?'text-amber-300':'text-rose-300') }}">{{ $assessment['label'] }}</h2><p class="mt-1 text-xs text-slate-500">Analiză pe putere, porniri, energie zilnică și backup · scor {{ $assessment['score'] }}%</p></div></div><div class="grid grid-cols-2 gap-2 sm:grid-cols-4"><div class="rounded-xl bg-slate-950/50 px-3 py-2"><small class="block text-[9px] text-slate-600">SOLAR / ZI</small><b class="text-xs text-amber-300">{{ $assessment['daily_solar_kwh'] }} kWh</b></div><div class="rounded-xl bg-slate-950/50 px-3 py-2"><small class="block text-[9px] text-slate-600">CONSUM / ZI</small><b class="text-xs text-sky-300">{{ $assessment['daily_load_kwh'] }} kWh</b></div><div class="rounded-xl bg-slate-950/50 px-3 py-2"><small class="block text-[9px] text-slate-600">VÂRF</small><b class="text-xs">{{ number_format($assessment['peak_w']/1000,2) }} kW</b></div><div class="rounded-xl bg-slate-950/50 px-3 py-2"><small class="block text-[9px] text-slate-600">AUTONOMIE</small><b class="text-xs text-violet-300">{{ $assessment['backup_hours'] }} h</b></div></div></div>
    <div class="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-4">@foreach($assessment['checks'] as $check)<div class="flex items-center gap-2 rounded-xl border border-slate-800/70 bg-slate-950/30 p-3"><span class="grid size-6 place-items-center rounded-full text-xs {{ $check['ok']?'bg-emerald-400/15 text-emerald-300':'bg-rose-400/15 text-rose-300' }}">{{ $check['ok']?'✓':'×' }}</span><div><b class="block text-[10px]">{{ $check['name'] }}</b><small class="text-[9px] text-slate-600">necesar {{ $check['required'] }} / disponibil {{ $check['available'] }} {{ $check['unit'] }}</small></div></div>@endforeach</div>
    @if(count($assessment['recommendations']))<div class="mt-4 rounded-xl bg-slate-950/40 p-3 text-xs text-amber-200"><b>Recomandare:</b> {{ implode(' ', $assessment['recommendations']) }}</div>@endif
   </div>
   <div class="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><template x-for="m in [{l:'Producție solară',v:formatW(result.solar_w),c:'text-amber-300',i:'☀'},{l:'Consum casă',v:formatW(result.served_load_w),c:'text-sky-300',i:'⌂'},{l:batteryDirection,v:(result.battery_w>0?'+':result.battery_w<0?'−':'')+formatW(result.battery_w),c:'text-violet-300',i:'▣'},{l:gridLabel,v:formatW(result.grid_w),c:'text-rose-300',i:'⌁'},{l:'SOC baterie',v:Number(result.soc).toFixed(1)+'%',c:'text-emerald-300',i:'⚡'}]"><div class="glass rounded-2xl p-4"><div class="mb-3 flex items-center justify-between text-xs text-slate-500"><span x-text="m.l"></span><span x-text="m.i" class="text-lg"></span></div><div class="text-2xl font-extrabold" :class="m.c" x-text="m.v"></div></div></template></div>
   <div class="grid gap-5 xl:grid-cols-[1fr_330px]">
    <div class="glass grid-bg relative min-h-[480px] overflow-hidden rounded-3xl p-5 sm:p-8">
     <div class="absolute left-6 top-5 text-[10px] font-extrabold uppercase tracking-[.2em] text-slate-600">Arhitectura fluxului</div><div class="absolute right-6 top-5 flex items-center gap-2 text-[10px] font-bold text-emerald-400"><i class="size-2 rounded-full bg-emerald-400"></i>LIVE</div>
     <div class="relative mx-auto mt-9 h-[390px] w-full max-w-3xl">
      <div class="node absolute left-1/2 top-0 w-44 -translate-x-1/2 rounded-2xl border border-amber-400/20 bg-amber-400/8 p-4 text-center"><div class="text-3xl">☀️</div><div class="mt-1 text-[10px] font-bold tracking-widest text-amber-300">SOLAR ARRAY</div><div class="text-xl font-extrabold" x-text="formatW(result.solar_w)"></div><div class="text-[10px] text-slate-500" x-text="installedW/1000+' kWp instalați'"></div></div>
      <div class="flow-line flow-solar left-1/2 top-[106px] h-[50px] w-[3px] -translate-x-1/2" :style="`opacity:${result.solar_w?1:.12}`"></div>
      <div class="node absolute left-1/2 top-[150px] w-48 -translate-x-1/2 rounded-2xl border border-sky-400/20 bg-sky-400/8 p-4 text-center"><div class="text-2xl">◈</div><div class="text-[10px] font-bold tracking-widest text-sky-300">INVERTOR HIBRID</div><div class="text-sm font-extrabold">Deye 3.6 kW</div><div class="mt-2 h-1 overflow-hidden rounded-full bg-slate-800"><div class="h-full bg-sky-400" :style="`width:${Math.min(100,result.solar_w/36)}%`"></div></div></div>
      <div class="flow-line flow-battery left-[21%] top-[258px] w-[29%] -rotate-[18deg]" :style="`opacity:${result.battery_w?1:.12};height:${Math.max(2,Math.min(7,Math.abs(result.battery_w)/400))}px`"></div><div class="flow-line flow-house left-1/2 top-[250px] h-[47px] w-[3px] -translate-x-1/2" :style="`opacity:${result.served_load_w?1:.12}`"></div><div class="flow-line flow-grid left-1/2 top-[258px] w-[29%] rotate-[18deg]" :style="`opacity:${result.grid_w?1:.12};height:${Math.max(2,Math.min(7,Math.abs(result.grid_w)/400))}px`"></div>
      <div class="node absolute bottom-0 left-0 w-[29%] rounded-2xl border border-violet-400/20 bg-violet-400/8 p-4 text-center"><div class="text-2xl">🔋</div><div class="text-[10px] font-bold tracking-widest text-violet-300">BATERIE</div><div class="text-lg font-extrabold" x-text="Number(result.soc).toFixed(1)+'%'"></div><div class="mt-2 h-2 rounded-full bg-slate-800"><div class="h-full rounded-full bg-gradient-to-r from-violet-500 to-emerald-400" :style="`width:${result.soc}%`"></div></div></div>
      <div class="node absolute bottom-0 left-1/2 w-[29%] -translate-x-1/2 rounded-2xl border border-sky-400/20 bg-sky-400/8 p-4 text-center"><div class="text-2xl">🏠</div><div class="text-[10px] font-bold tracking-widest text-sky-300">CASĂ</div><div class="text-lg font-extrabold" x-text="formatW(result.served_load_w)"></div><div class="text-[10px] text-slate-500" x-text="result.shed_loads.length?result.shed_loads.length+' sarcini oprite':'Toate sarcinile alimentate'"></div></div>
      <div class="node absolute bottom-0 right-0 w-[29%] rounded-2xl border border-rose-400/20 bg-rose-400/8 p-4 text-center"><div class="text-2xl">⚡</div><div class="text-[10px] font-bold tracking-widest text-rose-300">REȚEA</div><div class="text-lg font-extrabold" x-text="gridAvailable?formatW(result.grid_w):'OFFLINE'"></div><div class="text-[10px] text-slate-500" x-text="gridMode.replace('_',' ').toUpperCase()"></div></div>
     </div>
    </div>
    <div class="space-y-5"><div class="glass rounded-3xl p-5"><div class="mb-4 flex items-center justify-between"><h2 class="font-bold">Simulator de timp</h2><span :class="running?'text-emerald-300':'text-amber-300'" class="text-[10px] font-bold" x-text="running?'RULEAZĂ':'PAUZĂ'"></span></div><div class="rounded-2xl bg-slate-950/70 p-4 text-center"><div class="font-mono text-2xl font-extrabold" x-text="time.toLocaleTimeString('ro-RO',{hour:'2-digit',minute:'2-digit'})"></div><div class="mt-1 text-xs text-slate-500" x-text="time.toLocaleDateString('ro-RO',{weekday:'long',day:'numeric',month:'long',year:'numeric'})"></div></div><div class="mt-4 grid grid-cols-4 gap-2"><button @click="play" class="rounded-xl bg-emerald-500 py-2 text-sm font-extrabold text-slate-950">▶</button><button @click="pause" class="rounded-xl bg-slate-800 py-2">Ⅱ</button><button @click="stop" class="rounded-xl bg-slate-800 py-2">■</button><button @click="reset" class="rounded-xl bg-slate-800 py-2">↻</button></div><div class="mt-3 grid grid-cols-5 gap-1"><template x-for="s in [1,10,60,360,1440]"><button @click="speed=s" :class="speed===s?'bg-sky-500 text-slate-950':'bg-slate-900 text-slate-500'" class="rounded-lg py-2 text-[10px] font-extrabold" x-text="s+'×'"></button></template></div><div class="mt-4 grid grid-cols-2 gap-2"><select x-model="weather" @change="tick" class="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-xs"><option value="clear">Senin</option><option value="partly_cloudy">Parțial noros</option><option value="cloudy">Noros</option><option value="rain">Ploaie</option><option value="fog">Ceață</option><option value="snow">Zăpadă</option></select><select x-model="gridMode" @change="gridAvailable=gridMode!=='offline';tick()" class="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-xs"><option value="prosumer">Prosumator</option><option value="zero_export">Zero export</option><option value="offline">Offline</option></select></div><label class="mt-3 flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" x-model="randomWeather" @change="tick" class="accent-sky-400"> Vreme aleatorie</label></div>
     <div class="glass rounded-3xl p-5"><h2 class="mb-4 font-bold">Scor energetic</h2><div class="grid grid-cols-3 gap-3"><template x-for="m in [{n:'Independență',v:result.metrics.independence,c:'#34d399'},{n:'Solar util.',v:result.metrics.solar_utilization,c:'#fbbf24'},{n:'Rețea',v:result.metrics.grid_dependency,c:'#fb7185'}]"><div class="text-center"><div class="metric-ring mx-auto grid size-16 place-items-center rounded-full" :style="`--value:${m.v};--ring:${m.c}`"><div class="grid size-12 place-items-center rounded-full bg-[#0d1422] text-xs font-extrabold" x-text="m.v+'%'"></div></div><div class="mt-2 text-[9px] text-slate-500" x-text="m.n"></div></div></template></div><div class="mt-4 flex items-center justify-between rounded-xl bg-slate-950/70 p-3"><span class="text-xs text-slate-500">ENERGY SCORE</span><span class="text-3xl font-black text-emerald-300" x-text="result.metrics.score"></span></div></div>
    </div>
   </div>
   <div class="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><div class="glass rounded-3xl p-5"><div class="mb-4 flex items-center justify-between"><div><h2 class="font-bold">Power Flow</h2><p class="text-xs text-slate-500">Putere instantanee în wați</p></div><div class="flex gap-2 text-[10px]"><span class="rounded-lg bg-amber-400/10 px-2 py-1 text-amber-300" x-text="energy.solar.toFixed(2)+' kWh solar'"></span><span class="rounded-lg bg-rose-400/10 px-2 py-1 text-rose-300" x-text="energy.import.toFixed(2)+' kWh import'"></span></div></div><div class="h-64"><canvas x-ref="powerChart"></canvas></div></div><div class="glass rounded-3xl p-5"><h2 class="font-bold">Battery SOC</h2><p class="mb-3 text-xs text-slate-500">Fereastră operațională 10–100%</p><div class="h-64"><canvas x-ref="socChart"></canvas></div></div></div>
   <div class="mt-5 grid gap-5 lg:grid-cols-2"><div class="glass rounded-3xl p-5"><div class="mb-4 flex items-center justify-between"><h2 class="font-bold">Consumatori backup / EPS</h2><button @click="tab='consumers'" class="text-xs font-bold text-sky-400">Vezi toți →</button></div><div class="grid gap-2 sm:grid-cols-2"><template x-for="c in consumers.filter(x=>x.is_essential).slice(0,6)"><button @click="toggleActive(c.id)" class="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/40 p-3 text-left"><span><b class="block text-xs" x-text="c.name"></b><small class="text-[10px] text-slate-500" x-text="formatW(c.nominal_power_w)+' · P'+c.priority"></small></span><i :class="activeConsumers.includes(c.id)?'bg-emerald-400':'bg-slate-700'" class="size-2 rounded-full"></i></button></template></div></div><div class="glass rounded-3xl p-5"><h2 class="mb-4 font-bold">Event Log</h2><div class="scrollbar h-44 space-y-2 overflow-y-auto pr-2"><template x-for="(log,i) in logs" :key="i"><div class="flex gap-3 border-b border-slate-800/70 pb-2 text-xs"><span class="font-mono text-slate-600" x-text="time.toLocaleTimeString('ro-RO')"></span><span :class="log.level==='CRITICAL'?'text-rose-400':log.level==='WARNING'?'text-amber-300':'text-slate-400'" class="font-bold" x-text="log.level"></span><span class="text-slate-400" x-text="log.message"></span></div></template></div></div></div>
  </section>
  <section x-show="tab==='panels'" x-cloak><div class="grid gap-5 xl:grid-cols-[1fr_340px]"><div class="glass rounded-3xl p-6"><div class="mb-7"><h2 class="text-xl font-extrabold">Garaj · Matrice solară 2 × 3</h2><p class="text-sm text-slate-500">Activează sloturile și proiectează upgrade-ul sistemului.</p></div><div class="grid grid-cols-3 gap-4"><template x-for="slot in [1,2,3,4,5,6]"><button @click="panels.find(p=>p.slot===slot)?togglePanel(panels.find(p=>p.slot===slot)):null" :class="panels.find(p=>p.slot===slot)?.enabled?'border-sky-400/40 bg-gradient-to-br from-sky-400/20 to-indigo-500/10':'border-dashed border-slate-700 bg-slate-950/30'" class="group aspect-[1.5] rounded-2xl border p-4 transition hover:border-sky-400/50"><template x-if="panels.find(p=>p.slot===slot)"><div><div class="grid grid-cols-4 gap-1"><template x-for="i in 12"><i class="aspect-square rounded-sm border border-sky-300/15 bg-sky-300/10"></i></template></div><div class="mt-3 text-xs font-extrabold" x-text="panels.find(p=>p.slot===slot).enabled?'505 W · S 35°':'DEZACTIVAT'"></div></div></template><template x-if="!panels.find(p=>p.slot===slot)"><div class="grid h-full place-items-center text-slate-600"><span><b class="block text-2xl">＋</b><small>Slot liber</small></span></div></template></button></template></div></div><div class="space-y-5"><div class="glass rounded-3xl p-6"><h3 class="font-bold">Capacitate matrice</h3><div class="mt-5 space-y-4"><div class="flex justify-between text-sm"><span class="text-slate-500">Instalată</span><b class="text-amber-300" x-text="(installedW/1000).toFixed(2)+' kWp'"></b></div><div class="flex justify-between text-sm"><span class="text-slate-500">Potențial</span><b>3.03 kWp</b></div><div class="flex justify-between text-sm"><span class="text-slate-500">Sloturi ocupate</span><b x-text="panels.length+' / 6'"></b></div><div class="h-2 rounded-full bg-slate-800"><div class="h-full rounded-full bg-gradient-to-r from-amber-400 to-sky-400" :style="`width:${panels.length/6*100}%`"></div></div></div></div><div class="glass rounded-3xl p-6"><h3 class="font-bold">Configurație</h3><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Orientare</dt><dd>Sud</dd></div><div class="flex justify-between"><dt class="text-slate-500">Înclinație</dt><dd>35°</dd></div><div class="flex justify-between"><dt class="text-slate-500">Pierderi sistem</dt><dd>15%</dd></div><div class="flex justify-between"><dt class="text-slate-500">Wattaj panou</dt><dd>505 W</dd></div></dl></div></div></div></section>
  <section x-show="tab==='consumers'" x-cloak><div class="glass rounded-3xl p-6"><div class="mb-6 flex items-end justify-between"><div><h2 class="text-xl font-extrabold">Consumatori electrici</h2><p class="text-sm text-slate-500">Comandă manual sarcinile și configurează prioritățile EPS.</p></div><span class="rounded-xl bg-sky-400/10 px-3 py-2 text-xs font-bold text-sky-300" x-text="consumers.length+' dispozitive'"></span></div><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><template x-for="c in consumers"><button @click="toggleActive(c.id)" :class="activeConsumers.includes(c.id)?'border-emerald-400/30 bg-emerald-400/5':'border-slate-800 bg-slate-950/40'" class="flex items-center gap-4 rounded-2xl border p-4 text-left transition"><div :class="c.is_essential?'bg-amber-400/10 text-amber-300':'bg-sky-400/10 text-sky-300'" class="grid size-11 place-items-center rounded-xl text-xl" x-text="c.is_essential?'⚡':'⌁'"></div><div class="min-w-0 flex-1"><b class="block truncate text-sm" x-text="c.name"></b><span class="text-[10px] text-slate-500" x-text="formatW(c.nominal_power_w)+' · '+c.mode+' · P'+c.priority"></span></div><span :class="activeConsumers.includes(c.id)?'bg-emerald-400':'bg-slate-700'" class="size-3 rounded-full"></span></button></template></div></div></section>
 </div>
</main></div></body></html>
